config/routes.rb
Rottenpotatoes::Application.routes.draw do

  resources :projects
  root :to => redirect('/projects')

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  helper_method :sort_column, :sort_direction


  def show
    id = params[:id] # retrieve project task ID from URI route
    @project = Project.find(id) # look up project task by unique ID
    # will render app/views/projects/show.<extension> by default
  end

  def index
    @projects = Project.order(sort_column + " " + sort_direction)
    if  params[:users]
      @projects = @projects.where(user: params[:users].map{|k, v| k})
    end
    @users = Project.pluck(:user).uniq

   # binding.pry
  end

  def new
    # default: render 'new' template
  end

  def create
    @project = Project.create!(params[:project])
    flash[:notice] = "#{@project.title} was successfully created."
    redirect_to projects_path
  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]
    @project.update_attributes!(params[:project])
    flash[:notice] = "#{@project.title} was successfully updated."
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project '#{@project.title}' deleted."
    redirect_to projects_path
  end

protected 

  def sort_column
    Project.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    css_class ||= "current"
    link_to title, {:sort => column, :direction => direction, :users => params[:users]}, {:class => css_class}
   end



end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Class Project Manager
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Class Project Manager
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/projects/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Project Task

= form_tag project_path(@project), :method => :put do

  = label :project, :title, 'Title'
  = text_field :project, 'title'

  = label :project, :description, 'Description'
  = text_field :project, 'description'

  = label :project, :extended_description, 'extended_description'
  = text_area :project, 'extended_description'

  = label :project, :user, 'Assigned User'
  = select :project, :user, ['Coulson','May','Ward','Skye','Fitz', 'Simmons']

  = label :project, :due_date, 'Due Date'
  = date_select :project, :due_date

  = submit_tag 'Update Project Task Info'

%br
=link_to "Back", project_path(@project)

app/views/projects/index.html.haml
-#  This file is app/views/projects/index.html.haml
%h1 All Project Tasks

= form_tag projects_url, :method => :get do
  Include:
  = hidden_field_tag "direction", params[:direction]
  = hidden_field_tag "sort",  params[:sort]
  - @users.each do |user|
    = user
    - if params[:users]
      = check_box_tag "users[#{user}]", 1, params[:users] && params[:users][user] == '1'
    -else
      = check_box_tag "users[#{user}]", 1, true, id: "users_#{user}"

  = submit_tag 'Filter'



%table#projects
  %thead
    %tr
      %th 
        = sortable "title", "Task Title"
      %th Task Details
      %th Assigned User
      %th 
        = sortable "due_date", "Due Date"

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.title 
        %td= link_to "More about #{project.title}", project_path(project)
        %td= project.user
        %td= project.due_date.to_formatted_s(:long)

= link_to 'Add new project task', new_project_path

app/views/projects/new.html.haml
%h1 Create New Project Task

= form_tag projects_path do

  = label :project, :title, 'Title'
  = text_field :project, 'title'

  = label :project, :description, 'Description'
  = text_field :project, 'description'

  = label :project, :extended_description, 'Extended Description'
  = text_area :project, 'extended_description'
  
  = label :project, :user, 'Assigned User'
  = select :project, :user, ['Coulson','May','Ward','Skye','Fitz', 'Simmons']

  = label :project, :due_date, 'Due Date'
  = date_select :project, :due_date

  = submit_tag 'Save Changes'

=link_to "Back", projects_path

app/views/projects/show.html.haml
-# in app/views/projects/show.html.haml

%h2 Details about #{@project.title}

%ul#details
  %li
    Assigned User:
    = @project.user
  %li
    Due by:
    = @project.due_date.strftime("%B %d, %Y")

%h3 Short Description:
%p#description= @project.description
 
%h3 Description:

%p#extended_description= @project.extended_description

= link_to 'Edit', edit_project_path(@project)
= button_to 'Delete', project_path(@project), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to project task list', projects_path